trigger:
- main

pool: default

stages:
  - stage: terraforminstall
    displayName: terraform inatall
    jobs:
      - job: terraformintall
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'


  - stage: terraformdeploy
    displayName: Terraformdeploy
    dependsOn: terraforminstall
    jobs:
      - job: terraforminit
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'tcs_infra'
            backendAzureRmOverrideSubscriptionID: '1a39c6ac-4bf8-406a-be20-298e2ae5b5ce'
            backendAzureRmResourceGroupName: 'tcs-rg'
            backendAzureRmStorageAccountName: 'tcsstg1'
            backendAzureRmContainerName: 'tcscon'
            backendAzureRmKey: 'terraform.tfstate'

      - job: terraformvalidate
        dependsOn: terraforminit
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'

      - job: terraformplan
        dependsOn: terraformvalidate
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'tcs_infra'

  - stage: scanning
    dependsOn: terraformdeploy
    jobs:
      - job: tfsec
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
            dir: '$(System.DefaultWorkingDirectory)'

  - stage: manualvalidation
    dependsOn: scanning
    jobs:
      - job: manualvalidation
        pool: server
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'nsn.kapil@gmail.com'
            approvers: 'nsn.kapil@gmail.com'
            instructions: 'pls approve'
            onTimeout: 'resume'



