trigger:
- main

pool: default

stages:
  - stage: terraforminittoplan
    displayName: terraform installation
    jobs: 
    - job: terraforminstall
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
    - job: terrafrominit
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'hclsc'
          backendAzureRmStorageAccountName: 'ztestg'
          backendAzureRmContainerName: 'ztecon'
          backendAzureRmKey: 'terraform.tfstate'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'validate'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          environmentServiceNameAzureRM: 'hclsc'
  - stage: 
    displayName: manual validation
    jobs:
      - job: manualvalidation
        pool: server
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'nsn.kpil@gmail.com'
            approvers: 'nsn.kapil@gmail.com'
            instructions: 'pls approve'
            onTimeout: 'resume'
  - stage: 
    displayName: sccaning
    jobs:
      - job: scanning
        pool: default
        steps:
        - script: |
            brew install tfsec
            tfsec .
          displayName: Run tfsec Scan
  - stage: 
    displayName: terraformapply
    jobs:
      - job: terraforminit
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'hclsc'
            backendAzureRmStorageAccountName: 'ztestg'
            backendAzureRmContainerName: 'ztecon'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTask@5
          displayName: Terraform Apply
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
            commandOptions: '-auto-approve'
            environmentServiceNameAzureRM: 'hclsc'


